services:
  flask:
    build: ./flask-app
    container_name: flask-image-uploader
    ports:
      - "5000:5000"
    volumes:
      - ./flask-app:/app
    networks:
      - app-network

  react:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
